[package]
name = "ag_playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autograd = { version = "2.0.0-rc3", features = ["blas", "accelerate", "intel-mkl"] }
